server:
  port: 8001
  servlet:
    context-path: /flowable
spring:
  application:
    name: flowable-demo

  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useSSL=false&serverTimezone=UTC
    username: root
    password: stormshensu
    driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  async-executor-activate: false #close schedule job
  #  When set databaseSchemaUpdate ture
  #  flowable detects inconsistencies between the library and database table structures,
  # it will automatically upgrade the database table structure to a new version
  database-schema-update: true
  history-level: full
  process:
    servlet:
      path: /service